import { enumFactory } from '../../../common/TypeUtils';
export default enumFactory({
  ONLINE: '已上架',
  OFFLINE: '已下架',
  INIT: '待完善',
  PENDING: '待上架',
  AUDIT: '待商户确认',
  RETURNED: '已退回',
  EFFECT: '处理中',
  FAILED_ONLINE: '上架失败',
  'ONLINE-EFFECT': '已上架-处理中',
  'ONLINE-CONFIRM': '已上架-待商家确认',
  'ONLINE-RETURN': '已上架-已退回',
  'FAILED-MODIFY': '已上架-修改失败',
  PAUSE: '已暂停',
  'PAUSE-CONFIRM': '已暂停-待商家确认',
  'PAUSE-RETURN': '已暂停-已退回',
  'PAUSE-EFFECT': '已暂停-处理中',
  'PAUSE-FAILED': '已暂停-修改失败',
  CAMP_CREATED: '处理中',
  CAMP_CONFIRM: '待商家确认',
  CAMP_AUDITING: '审核中',
  CAMP_TIME_YET: '已发布未开始',
  CAMP_GOING: '已发布已开始',
  CAMP_MODIFYING: '活动修改中',
  CAMP_CLOSING: '活动下架中',
  CAMP_PAUSED: '已暂停',
  CAMP_ENDED: '已结束',
  CAMP_EXPIRED: '已结束',
  CAMP_AUDIT_FAIL: '审核失败',
  CAMP_REJECTED: '已驳回',
});
