import React from 'react';

/* 抽取原NewShop和NewMall的并集 */
export default {
  INVALID_PARAMETER: '参数无效',
  SYSTEM_ERROR: '系统异常',
  BRAND_NOT_EXISTS: '店铺创建场景下品牌不存在',
  CATOGORY_NOT_EXISTS: '门店品类不存在',
  ILLEGAL_BIZ_ORDER_STATUS: '流水订单状态非法',
  OPERATOR_NOT_PERMISSION: '暂无权限',
  STAFF_MERCHANT_RELATION_INVALID: '没有找到员工、商户关系',
  STAFF_JOB_NOT_EXIST: '暂无权限',
  SHOP_OPERATOR_AREA_NOT_INIT: '您的岗位尚未配置区域约束，暂无法操作',
  AREA_NOT_MATCH: '该门店所在的区域不在您的服务区域内，暂无法操作',
  SHOP_OPERATOR_CATEGORY_NOT_INIT: '您的岗位尚未配置类目约束，暂无法操作',
  SHOP_OPERATOR_CATEGORY_NOT_MATCH: '该门店所属类目不在您的服务范围内，暂无法操作',
  LICENSE_EXPIRES: '您提交的营业执照已过期',
  LICENSE_PRINCIPAL_NOT_MATCH: '您提交的营业执照信息与你的账号不一致',
  LICENSE_ADDRESS_NOT_MATCH: '您提交的营业执照信息地址有误',
  LICENSE_CHECK_FAIL: '您提交的营业执照存在问题，请重新提交',
  LICENSE_IS_REQUIRED: '请填写营业执照认证信息',
  CERTIFICATE_IS_REQUIRED: '请填写许可证认证信息',
  SHOP_CATEGORY_NOT_MATCH_CITY: '暂无权限',
  SHOP_BRAND_PROTECTED: '您提交的品牌已受保护，无法创建',
  LOCATION_VALIDATE_FAIL: '您填写的地址与地图定位差距太大，请修改',
  EXIST_FORBIDDEN_WORD: '您填写的内容包含敏感词，请修改',
  MERCHANT_NOT_EXIST: '商户不存在',
  SHOP_CTU_RISK: '当前门店存在风险，请联系口碑客服人员',
  UNIQUE_CONSTRAINT_SHOP_ERROR: '门店已存在，请确认后重新填写',
  UNIQUE_CONSTRAINT_IMPLEMENTID_ERROR: '机具号已存在，请确认后重新填写',
  UNIQUE_CONSTRAINT_OUTSHOPID_ERROR: '门店编号已存在，请确认后重新填写',
  SHOP_JUDGE_FAIL: <span>门店已存在，请联系口碑<a target="_blank" href="https://cschannel.alipay.com/newPortal.htm?scene=kb_0009">在线客服</a></span>,
  SHOP_STATUS_CANOT_MODIFY: '门店状态无法修改',
  PROVINCE_CITY_CANOT_MODIFY: '省市信息不允许修改',
  CATEGORY_CANOT_MODIFY: '类目信息不允许修改',
  NOT_ALLOWED_CONCURRENT_MODIFY: '门店修改审核中，无法操作',
  SHOP_STAFF_RELATION_CHECK_FAIL: '暂无权限',
  LEADS_NOT_EXIST: 'leads不存在',
  LEADS_STATUS_CAN_NOT_OP: '当前leads状态无法修改',
  SHOP_CREATE_INFO_NOT_MATCH_LEADS: 'leads开店部分信息跟leads不一致',
  NOT_SUPPORTED_BUSINESS: '系统异常',
  SHOP_INVALID_STATUS: '当前门店状态异常，无法操作',
  OPERATOR_AREA_NOT_INIT: '您的岗位尚未配置权限，暂无法操作',
  OPERATOR_CATEGORY_NOT_INIT: '您的岗位尚未配置类目约束，暂无法操作',
  CATEGORY_NOT_MATCH: '该门店所属行业不在您的服务范围内，暂无法操作',
  ORIGINAL_PRINCIPAL_RELATION_NOT_EXIST: '当前员工与门店不存在关联，无需操作',
  TARGET_PRINCIPAL_RELATION_EXIST: '当前门店与员工的关系已存在，无需重复操作',
  LEADS_HAS_RELEASE: '该门店对应leads已被释放回公海，请重新认领',
  LICENSE_CODE_REPEAT_ERROR: '该证照已被使用，不可重复用于开店。',
  BRAND_CATEGORY_NOT_MATCH: '您选择的品牌不属于该类目，请重新选择',
  LEADS_NOT_BELONG: '该leads已不在您的私海中，无法继续开店',
  SHOP_HAS_SURROUNDED_MALL: '该门店已归属该综合体，无需重复操作',
  SHOP_HAS_SURROUNDED_ANOTHER_MALL: '该门店已归属其他综合体，无法添加',
  MERCHANT_CAN_NOT_SIGN_KOUBEI: '您当前账户已签约支付宝，无法继续开店，请更换其他账户来开店或拨打400-826-7710热线，咨询或免费解约',
  USER_HAS_NOT_PERMISSION: '暂无权限',
  BRANCH_SHOP_NAME_CANNOT_CONTAIN_HEAD_NAME: '分店名不可包含主店名，请按示例进行填写',
  BRANCH_SHOP_NAME_CANNOT_PARENTHESES: '分店名不可包含括号，请按示例进行填写',
};
